clementine/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path("", include("core.urls")),
    path("", include("radio.urls")),
    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path

from core.views import HomePageView


app_name = "core"
urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
]

radio/urls.py
from django.urls import path

from radio.views import ArtistsPageView, PlatformsPageView, SongsPageView


app_name = "radio"
urlpatterns = [
    path("artists", ArtistsPageView.as_view(), name="artists_list"),
    path("artists/<letter>", ArtistsPageView.as_view(), name="artists_list"),
    path("platforms", PlatformsPageView.as_view(), name="platforms_list"),
    path("songs", SongsPageView.as_view(), name="songs_list"),
    path("songs/<letter>", SongsPageView.as_view(), name="songs_list"),
]

radio/models.py
from django.contrib.auth.models import User
from django.db import models

from core.models import MetaModel, Status


class Platform(models.Model):
    name = models.CharField(max_length=64, unique=True)
    description = models.TextField()
    symbol = models.ImageField(upload_to="platforms/symbols", blank=True, null=True)
    image = models.ImageField(upload_to="platforms/images", blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["name"]


class Label(MetaModel):
    name = models.CharField(
        max_length=40,
        unique=True,
        db_index=True,
        verbose_name="* Name",
        help_text="Name of this label, as you want it to appear on the site",
    )
    found_date = models.DateField(
        help_text="Date label was formed (YYYY-MM-DD)", null=True, blank=True
    )
    cease_date = models.DateField(
        help_text="Date label was closed/went out of business (YYYY-MM-DD)",
        null=True,
        blank=True,
    )
    info = models.TextField(
        blank=True, help_text="Additional information about this label. No HTML."
    )
    pouetid = models.IntegerField(
        blank=True,
        null=True,
        verbose_name="Pouet ID",
        help_text="If this label has a pouet group entry, enter the ID here.",
    )
    hol_id = models.IntegerField(
        blank=True,
        null=True,
        verbose_name="H.O.L. ID",
        help_text="Hall of Light ID number (Amiga) - See http://hol.abime.net",
    )
    label_icon = models.ImageField(
        upload_to="media/labels/icons",
        blank=True,
        null=True,
        verbose_name="Label Icon (Shows instead of default icon)",
        help_text="Upload an image containing the icon for this label",
    )
    logo = models.ImageField(
        upload_to="media/labels",
        blank=True,
        null=True,
        verbose_name="Label Logo",
        help_text="Upload an image containing the logo for this label",
    )
    status = models.ForeignKey(Status, null=True, on_delete=models.SET_NULL)
    webpage = models.URLField(
        blank=True,
        verbose_name="Website",
        help_text="Website for this label, if available",
    )
    wiki_link = models.URLField(
        blank=True, help_text="Full URL to wikipedia entry (if available)"
    )
    # ~ links = generic.GenericRelation(GenericLink)

    def __str__(self):
        return self.name


class License(models.Model):
    name = models.CharField(max_length=50, verbose_name="Name")
    description = models.TextField(verbose_name="Description", blank=True)
    icon = models.ImageField(
        upload_to="licenses", blank=True, null=True, verbose_name="License icon"
    )
    url = models.URLField(verbose_name="License URL", null=True, blank=True)
    downloadable = models.BooleanField(default=False, verbose_name="Can be downloaded")

    def __str__(self):
        return self.name


class Group(MetaModel):
    name = models.CharField(
        max_length=80,
        unique=True,
        db_index=True,
        verbose_name="* Name",
        help_text="The name of this group as you want it to appear.",
    )
    found_date = models.DateField(
        verbose_name="Found Date",
        help_text="Date this group was formed (YYYY-MM-DD)",
        null=True,
        blank=True,
    )
    group_icon = models.ImageField(
        help_text="Group Icon (Shows instead of default icon)",
        upload_to="media/groups/icons",
        blank=True,
        null=True,
    )
    group_logo = models.ImageField(
        help_text="Logo/Pic Of This Group",
        upload_to="media/groups",
        blank=True,
        null=True,
    )
    info = models.TextField(
        blank=True,
        verbose_name="Group Info",
        help_text="Additional information on this group. No HTML.",
    )
    pouetid = models.IntegerField(
        verbose_name="Pouet ID",
        help_text="If this group has a Pouet entry, enter the ID number here - See http://www.pouet.net",
        blank=True,
        null=True,
    )
    status = models.ForeignKey(Status, null=True, on_delete=models.SET_NULL)
    webpage = models.URLField(
        blank=True,
        verbose_name="Website",
        help_text="Add the website address for this group, if one exists.",
    )
    wiki_link = models.URLField(
        blank=True, help_text="URL to wikipedia entry (if available)"
    )

    def __str__(self):
        return self.name


class Artist(MetaModel):
    handle = models.CharField(
        max_length=64,
        unique=True,
        db_index=True,
        verbose_name="* Handle",
        help_text="Artist handle/nickname. If no handle is used, place their real name here (and not in the above real name position) to avoid duplication",
    )
    name = models.CharField(
        max_length=64,
        blank=True,
        verbose_name="Name",
        help_text="Artist name (First and Last)",
    )
    alias_of = models.ForeignKey(
        "self", null=True, blank=True, related_name="aliases", on_delete=models.CASCADE
    )
    artist_pic = models.ImageField(
        verbose_name="Picture",
        help_text="Insert a picture of this artist.",
        upload_to="artists",
        blank=True,
        null=True,
    )
    deceased_date = models.DateField(
        help_text="Date of Passing (YYYY-MM-DD)",
        null=True,
        blank=True,
        verbose_name="Date Of Death",
    )
    dob = models.DateField(
        help_text="Date of Birth (YYYY-MM-DD)", null=True, blank=True
    )
    groups = models.ManyToManyField(
        Group,
        blank=True,
        help_text="Select any known groups this artist is a member of.",
    )
    hol_id = models.IntegerField(
        blank=True,
        null=True,
        verbose_name="H.O.L. ID",
        help_text="Hall of Light Artist ID number (Amiga) - See http://hol.abime.net",
    )
    home_country = models.CharField(
        blank=True,
        max_length=10,
        verbose_name="Country Code",
        help_text="Standard country code, such as gb, us, ru, se etc.",
    )
    home_location = models.CharField(
        blank=True,
        max_length=40,
        verbose_name="Location",
        help_text="Hometown location, if known.",
    )
    info = models.TextField(
        blank=True, help_text="Additional artist information. No HTML allowed."
    )
    labels = models.ManyToManyField(
        Label,
        blank=True,
        help_text="Select any known production labels associated with this artist.",
    )  # Production labels this artist has worked for
    last_fm_id = models.CharField(
        blank=True,
        max_length=32,
        verbose_name="Last.fm ID",
        help_text="If this artist has a Last.FM account, specify the username portion here. Use + instead of Space. Example: Martin+Galway",
    )
    link_to_user = models.OneToOneField(
        User, null=True, blank=True, on_delete=models.SET_NULL, related_name="User"
    )
    status = models.ForeignKey(Status, null=True, on_delete=models.SET_NULL)
    twitter_id = models.CharField(
        blank=True,
        max_length=32,
        verbose_name="Twitter ID",
        help_text="Enter the Twitter account name of the artist, if known (without the Twitter URL)",
    )
    webpage = models.URLField(
        blank=True,
        verbose_name="Website",
        help_text="Website for this artist. Must exist on the web.",
    )
    wiki_link = models.URLField(
        blank=True, help_text="URL to Wikipedia entry (if available)"
    )
    scene_relevance = models.TextField(
        blank=True,
        help_text="The artist's demoscene relevance. So the mods can approve it faster",
    )

    def __str__(self):
        return f"{self.id} - {self.handle}"

    @property
    def is_deceased(self):
        return self.deceased_date is not None


class Song(models.Model):
    LEGACY_FLAG = (
        (
            " ",
            "N/A",
        ),  # Is not a legacy tune (new upload since Jul. 2018, or replaced streamrip)
        (
            "R",
            "Recovered",
        ),  # is a recovered stream rip (not original, needs replacement)
        ("M", "Missing"),  # existed in Old Necta but is present now
    )

    title = models.CharField(
        verbose_name="* Song Name",
        help_text="The name of this song, as it should appear in the database",
        max_length=80,
        db_index=True,
    )
    bitrate = models.IntegerField(blank=True, null=True)
    explicit = models.BooleanField(
        default=False,
        verbose_name="Explicit Lyrics?",
        help_text="Place a checkmark in the box to flag this song as having explicit lyrics/content",
    )
    file = models.FileField(
        upload_to="media/songs",
        verbose_name="File",
        max_length=200,
        help_text="Select a module (mod, xm, etc...) or audio file (mp3, ogg, etc...) to upload. See FAQ for details.",
    )
    locked_until = models.DateTimeField(blank=True, null=True)
    loopfade_time = models.PositiveIntegerField(
        default=0, verbose_name="Forced play time", help_text="In seconds, 0 = disabled"
    )
    playback_fadeout = models.BooleanField(
        default=True,
        verbose_name="Fadeout at end",
        help_text="Only active if Forced play time is set",
    )
    playback_bass_mode = models.CharField(
        max_length=4,
        choices=(
            ("pt1", "ProTracker 1"),
            ("ft2", "FastTracker2"),
            ("bass", "Bass"),
        ),
        blank=True,
        verbose_name="Playback mode",
    )
    playback_bass_inter = models.CharField(
        max_length=6,
        choices=(("off", "Off"), ("linear", "Linear"), ("sinc", "Sinc")),
        blank=True,
        verbose_name="Playback interpolation",
    )
    playback_bass_mix = models.CharField(
        max_length=4,
        choices=(("Auto", "auto"), ("0.0", "Off"), ("0.3", "Mix"), ("0.5", "Mono")),
        blank=True,
        verbose_name="Playback Mix",
    )

radio/views.py
from string import ascii_lowercase

from django.views.generic import ListView

from .models import Artist, Platform, Song


class ArtistsPageView(ListView):
    paginate_by = 30
    context_object_name = "artists_list"

    def get_queryset(self):
        letter = self.kwargs.get("letter", "")
        if letter not in ascii_lowercase:
            return Artist.objects.filter(handle__iregex=r"^[^a-zA-Z].*$")

        return Artist.objects.filter(handle__startswith=letter)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["alphabet"] = ascii_lowercase + "-"

        return context


class PlatformsPageView(ListView):
    context_object_name = "platforms_list"
    model = Platform


class SongsPageView(ListView):
    paginate_by = 30
    context_object_name = "songs_list"

    def get_queryset(self):
        letter = self.kwargs.get("letter", "")
        if letter not in ascii_lowercase:
            return Song.objects.filter(title__iregex=r"^[^a-zA-Z].*$")

        return Song.objects.filter(title__startswith=letter)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["alphabet"] = ascii_lowercase + "-"

        return context

radio/templates/radio/artist_list.html
{% extends "base/base.html" %}

{% load static %}
{% load cache %}
{% load dv_extend %}

{% block main %}
<h2><img class="icon_header" src="{% static 'user_green.png' %}" alt="" />Complete Artist List</h2>

<p>
{% for letter in alphabet %}<a href="{% url 'radio:artists_list' letter %}">{{ letter|upper }}</a> {% endfor %} [<a href="{% url 'radio:artists_list' %}">All Artists</a>]
</p>

<p>
{% for artist in artists_list %}
<span>
    {% if artist.home_country %}
        {{ artist.home_country|safe }}
    {% else %}
        <img src="{% static 'user_green.png' %}" />
    {% endif %}
    <a href="#" {% if artist.alias_of %}title="Alias of {{artist.alias_of}}"{% else %}{% if artist.aliases.all %}title="Aliases : {% for alias in artist.aliases.all %}{{ alias.handle }} {% endfor %}"{% endif %}{% endif %}>{{ artist.handle }}{% if artist.name %} ({{ artist.name }}){% endif %}</a>
    {% if artist.is_deceased %}
        <img src="{% static 'deceased.png' %}" class="countryflag" title="Deceased {% if artist.deceased_date %}[On {{ artist.deceased_date|date:'F j, Y' }}]{% endif %}" />
    {% endif %}
    </span>
<br />
{% endfor %}
</p>

<p>
Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
    <p>
    {% if page_obj.has_previous %}
    <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
    {%else%}
    Previous
    {% endif %}

    {% for p in paginator %}
    {% if p.number == page_obj.number %}<b>{{ p.number }}</b>{% else %}<a href="?page={{ p.number }}">{{ p.number }}</a>{% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">Next</a>
    {%else%}
    Next
    {% endif %}
    </p>
</p>

<p>
Not Finding Who You're Looking For?
<a href="#">Suggest A New Artist!</a>
</p>
{% endblock %}

radio/templates/radio/platform_list.html
{% extends "base/base.html" %}

{% load static %}
{% load cache %}
{% load dv_extend %}

{% block main %}
<h2><img class="icon_header" src="{% static 'sound.png' %}" alt="" />Song Platforms</h2>

<p>
{% for platform in platforms_list %}
<img src="{{ platform.symbol.url }}" alt="{{ platform.name }}" />
<a href="#">{{ platform.name }}</a> (XX Songs)<br />
{% endfor %}
</p>

{% endblock %}

radio/templates/radio/song_list.html
{% extends "base/base.html" %}

{% load static %}
{% load cache %}
{% load dv_extend %}

{% block main %}
<h2><img class="icon_header" src="{% static 'music.png' %}" alt="" />List of Songs</h2>

<p>
{% for letter in alphabet %}<a href="{% url 'radio:songs_list' letter %}">{{ letter|upper }}</a> {% endfor %}
</p>

<table class="songlist sortable-onload-show-0">
<tr>
    <th class="sortable-text">Song Title</th>
    <th class="sortable-text">Artist</th>
    <th class="sortable-numeric">Song Length</th>
    <th class="sortable-text">Status</th>
    <th class="sortable-numeric">Vote</th>
    <th class="sortable-sortLocked">Queue</th>
    <th class="sortable-text">Last Request</th>
</tr>
{% for song in songs_list %}
<tr class="{# cycle 'row1' 'row2' #}">
    <td>{{ song.title }}</td>
    <td>
    {% for artist in song.artists.all %}{% with artist as A%}{% include "webview/t/artist.html" %}{% endwith %}{% if forloop.last %} {% else %}, {% endif %}{% endfor %}
    {% for group in song.groups.all %}{% with group as G%}{% include "webview/t/group.html" %}{% endwith %}{% if forloop.last %} {% else %}, {% endif %}{% endfor %}
    </td>
    <td>{{ song.length }}</td>
    <td>{{ song.get_status_display }}</td>
    <td>{{ song.rating|floatformat:1 }}</td>
    <td>
        <span data-name="a_queue_{{ song.id }}">
            <img class="song_head" src="{% static 'locki.png' %}" title="Song Locked" />
        </span>
    </td>
    <td><span class="lastreqdate">{{ song.last_queued|date:"Y-m-d" }}</span></td>
</tr>
{% endfor %}
</table>

<p>
Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
    <p>
    {% if page_obj.has_previous %}
    <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
    {%else%}
    Previous
    {% endif %}

    {% for p in paginator %}
    {% if p.number == page_obj.number %}<b>{{ p.number }}</b>{% else %}<a href="?page={{ p.number }}">{{ p.number }}</a>{% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">Next</a>
    {%else%}
    Next
    {% endif %}
    </p>
</p>
{% endblock %}