clementine/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path("", include("core.urls")),
    path("", include("radio.urls")),
    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path

from core.views import HomePageView


app_name = "core"
urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
]

radio/urls.py
from django.urls import path

from radio.views import ArtistsPageView, PlatformsPageView, SongsPageView


app_name = "radio"
urlpatterns = [
    path("artists", ArtistsPageView.as_view(), name="artists_list"),
    path("artists/<letter>", ArtistsPageView.as_view(), name="artists_list"),
    path("platforms", PlatformsPageView.as_view(), name="platforms_list"),
    path("songs", SongsPageView.as_view(), name="songs_list"),
    path("songs/<letter>", SongsPageView.as_view(), name="songs_list"),
]

core/models.py
from django.contrib.auth.models import User
from django.db import models


class MetaModel(models.Model):
    created_by = models.ForeignKey(
        User, null=True, blank=True, on_delete=models.SET_NULL
    )
    created_at = models.DateTimeField(
        auto_now_add=True, blank=True, null=True
    )
    last_updated = models.DateTimeField(
        auto_now=True, editable=False, blank=True, null=True
    )

    class Meta:
        abstract = True


class Status(models.Model):
    code = models.CharField(max_length=1)
    name = models.CharField(max_length=30)

    class Meta:
        verbose_name_plural = "Statuses"

    def __str__(self):
        return self.name


class News(MetaModel):
    title = models.CharField(max_length=100)
    text = models.TextField()
    status = models.ForeignKey(Status, null=True, on_delete=models.SET_NULL)
    icon = models.URLField(blank=True)

    class Meta:
        verbose_name_plural = "News"
        ordering = ["-created_at"]

    def __str__(self):
        return self.title


class UserProfile(models.Model):
    VISIBLE_TO = (("A", "All users"), ("R", "Registrered users"), ("N", "No one"))

    user = models.OneToOneField(User, unique=True, on_delete=models.CASCADE)
    real_name = models.CharField(
        blank=True,
        max_length=40,
        verbose_name="Real Name",
        help_text="Your real name (optional)",
    )
    last_ip = models.GenericIPAddressField(null=True, blank=True, default="")
    aol_id = models.CharField(
        blank=True,
        max_length=40,
        verbose_name="AOL IM",
        help_text="AOL IM ID, for people to contact you (optional)",
    )
    hol_id = models.IntegerField(
        blank=True,
        null=True,
        verbose_name="H.O.L. ID",
        help_text="If you have a Hall of Light ID number (Amiga Developers) - See http://hol.abime.net",
    )
    icq_id = models.CharField(
        blank=True,
        max_length=40,
        verbose_name="ICQ Number",
        help_text="ICQ Number for people to contact you (optional)",
    )
    yahoo_id = models.CharField(
        blank=True,
        max_length=40,
        verbose_name="Yahoo! ID",
        help_text="Yahoo! IM ID, for people to contact you (optional)",
    )
    twitter_id = models.CharField(
        blank=True,
        max_length=32,
        verbose_name="Twitter ID",
        help_text="Enter your Twitter account name, without the Twitter URL (optional)",
    )
    mastodon_id = models.CharField(
        blank=True,
        max_length=100,
        verbose_name="Mastodon ID",
        help_text="Enter your Mastodon complete account name, with the instance URL (optional)",
    )
    avatar = models.ImageField(upload_to="medias/avatars", blank=True, null=True)
    country = models.CharField(blank=True, max_length=10, verbose_name="Country code")
    location = models.CharField(
        blank=True, max_length=40, verbose_name="Hometown Location"
    )
    custom_css = models.URLField(blank=True)
    email_on_artist_add = models.BooleanField(
        default=True, verbose_name="Send email on artist approval"
    )
    email_on_artist_comment = models.BooleanField(
        default=True, verbose_name="Send email on artist comments"
    )
    email_on_group_add = models.BooleanField(
        default=True, verbose_name="Send email on group/label approval"
    )
    email_on_pm = models.BooleanField(default=True, verbose_name="Send email on new PM")
    fave_id = models.IntegerField(
        blank=True,
        null=True,
        verbose_name="Fave SongID",
        help_text="SongID number of *the* song you love the most!",
    )
    # ~ group = models.ForeignKey(Group, null = True, blank = True)
    infoline = models.CharField(blank=True, max_length=50)
    info = models.TextField(
        blank=True,
        verbose_name="Profile Info",
        help_text="Enter a little bit about yourself. No HTML. BBCode tags allowed",
    )
    last_active = models.DateTimeField(blank=True, null=True)
    last_activity = models.DateTimeField(blank=True, null=True, db_index=True)
    paginate_favorites = models.BooleanField(default=True)
    pm_accepted_upload = models.BooleanField(
        default=True, verbose_name="Send PM on accepted upload"
    )
    show_screenshots = models.BooleanField(
        default=True, verbose_name="Show Screenshots/Pouet Images in Currently Playing"
    )
    show_youtube = models.BooleanField(
        default=True, verbose_name="Show YouTube videoes in Currently Playing"
    )
    # ~ theme = models.ForeignKey(Theme, blank = True, null = True)
    token = models.CharField(blank=True, max_length=32)
    use_tags = models.BooleanField(verbose_name="Show tags", default=True)
    visible_to = models.CharField(max_length=1, default="A", choices=VISIBLE_TO)
    web_page = models.URLField(
        blank=True,
        verbose_name="Website",
        help_text="Your personal website address. Must be a valid URL",
    )
    hellbanned = models.BooleanField(default=False)
    # ~ links = generic.GenericRelation(GenericLink)

    def __str__(self):
        return self.user.username


class Theme(models.Model):
    title = models.CharField(max_length=20)
    active = models.BooleanField(default=True)
    description = models.TextField(blank=True)
    css = models.CharField(max_length=120)
    default = models.BooleanField(default=False)
    creator = models.ForeignKey(User, blank=True, null=True, on_delete=models.SET_NULL)
    # ~ screenshots = generic.GenericRelation("ScreenshotObjectLink")

    class Meta:
        ordering = ["-default", "title"]

    def __str__(self):
        return self.title


class Logo(models.Model):
    file = models.FileField(upload_to="logos")
    active = models.BooleanField(default=True, db_index=True)
    creator = models.CharField(max_length=60)
    description = models.TextField(blank=True)
    legacy = models.BooleanField(default=False)

    def __str__(self):
        return self.file.name

radio/models.py
from django.contrib.auth.models import User
from django.db import models

from core.models import MetaModel, Status


class Platform(models.Model):
    name = models.CharField(max_length=64, unique=True)
    description = models.TextField()
    symbol = models.ImageField(upload_to="platforms/symbols", blank=True, null=True)
    image = models.ImageField(upload_to="platforms/images", blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["name"]


class Label(MetaModel):
    name = models.CharField(
        max_length=40,
        unique=True,
        db_index=True,
        verbose_name="* Name",
        help_text="Name of this label, as you want it to appear on the site",
    )
    found_date = models.DateField(
        help_text="Date label was formed (YYYY-MM-DD)", null=True, blank=True
    )
    cease_date = models.DateField(
        help_text="Date label was closed/went out of business (YYYY-MM-DD)",
        null=True,
        blank=True,
    )
    info = models.TextField(
        blank=True, help_text="Additional information about this label. No HTML."
    )
    pouetid = models.IntegerField(
        blank=True,
        null=True,
        verbose_name="Pouet ID",
        help_text="If this label has a pouet group entry, enter the ID here.",
    )
    hol_id = models.IntegerField(
        blank=True,
        null=True,
        verbose_name="H.O.L. ID",
        help_text="Hall of Light ID number (Amiga) - See http://hol.abime.net",
    )
    label_icon = models.ImageField(
        upload_to="media/labels/icons",
        blank=True,
        null=True,
        verbose_name="Label Icon (Shows instead of default icon)",
        help_text="Upload an image containing the icon for this label",
    )
    logo = models.ImageField(
        upload_to="media/labels",
        blank=True,
        null=True,
        verbose_name="Label Logo",
        help_text="Upload an image containing the logo for this label",
    )
    status = models.ForeignKey(Status, null=True, on_delete=models.SET_NULL)
    webpage = models.URLField(
        blank=True,
        verbose_name="Website",
        help_text="Website for this label, if available",
    )
    wiki_link = models.URLField(
        blank=True, help_text="Full URL to wikipedia entry (if available)"
    )
    # ~ links = generic.GenericRelation(GenericLink)

    def __str__(self):
        return self.name


class License(models.Model):
    name = models.CharField(max_length=50, verbose_name="Name")
    description = models.TextField(verbose_name="Description", blank=True)
    icon = models.ImageField(
        upload_to="licenses", blank=True, null=True, verbose_name="License icon"
    )
    url = models.URLField(verbose_name="License URL", null=True, blank=True)
    downloadable = models.BooleanField(default=False, verbose_name="Can be downloaded")

    def __str__(self):
        return self.name


class Group(MetaModel):
    name = models.CharField(
        max_length=80,
        unique=True,
        db_index=True,
        verbose_name="* Name",
        help_text="The name of this group as you want it to appear.",
    )
    found_date = models.DateField(
        verbose_name="Found Date",
        help_text="Date this group was formed (YYYY-MM-DD)",
        null=True,
        blank=True,
    )
    group_icon = models.ImageField(
        help_text="Group Icon (Shows instead of default icon)",
        upload_to="media/groups/icons",
        blank=True,
        null=True,
    )
    group_logo = models.ImageField(
        help_text="Logo/Pic Of This Group",
        upload_to="media/groups",
        blank=True,
        null=True,
    )
    info = models.TextField(
        blank=True,
        verbose_name="Group Info",
        help_text="Additional information on this group. No HTML.",
    )
    pouetid = models.IntegerField(
        verbose_name="Pouet ID",
        help_text="If this group has a Pouet entry, enter the ID number here - See http://www.pouet.net",
        blank=True,
        null=True,
    )
    status = models.ForeignKey(Status, null=True, on_delete=models.SET_NULL)
    webpage = models.URLField(
        blank=True,
        verbose_name="Website",
        help_text="Add the website address for this group, if one exists.",
    )
    wiki_link = models.URLField(
        blank=True, help_text="URL to wikipedia entry (if available)"
    )

    def __str__(self):
        return self.name


class Artist(MetaModel):
    handle = models.CharField(
        max_length=64,
        unique=True,
        db_index=True,
        verbose_name="* Handle",
        help_text="Artist handle/nickname. If no handle is used, place their real name here (and not in the above real name position) to avoid duplication",
    )
    name = models.CharField(
        max_length=64,
        blank=True,
        verbose_name="Name",
        help_text="Artist name (First and Last)",
    )
    alias_of = models.ForeignKey(
        "self", null=True, blank=True, related_name="aliases", on_delete=models.CASCADE
    )
    artist_pic = models.ImageField(
        verbose_name="Picture",
        help_text="Insert a picture of this artist.",
        upload_to="artists",
        blank=True,
        null=True,
    )
    deceased_date = models.DateField(
        help_text="Date of Passing (YYYY-MM-DD)",
        null=True,
        blank=True,
        verbose_name="Date Of Death",
    )
    dob = models.DateField(
        help_text="Date of Birth (YYYY-MM-DD)", null=True, blank=True
    )
    groups = models.ManyToManyField(
        Group,
        blank=True,
        help_text="Select any known groups this artist is a member of.",
    )
    hol_id = models.IntegerField(
        blank=True,
        null=True,
        verbose_name="H.O.L. ID",
        help_text="Hall of Light Artist ID number (Amiga) - See http://hol.abime.net",
    )
    home_country = models.CharField(
        blank=True,
        max_length=10,
        verbose_name="Country Code",
        help_text="Standard country code, such as gb, us, ru, se etc.",
    )
    home_location = models.CharField(
        blank=True,
        max_length=40,
        verbose_name="Location",
        help_text="Hometown location, if known.",
    )
    info = models.TextField(
        blank=True, help_text="Additional artist information. No HTML allowed."
    )
    labels = models.ManyToManyField(
        Label,
        blank=True,
        help_text="Select any known production labels associated with this artist.",
    )  # Production labels this artist has worked for
    last_fm_id = models.CharField(
        blank=True,
        max_length=32,
        verbose_name="Last.fm ID",
        help_text="If this artist has a Last.FM account, specify the username portion here. Use + instead of Space. Example: Martin+Galway",
    )
    link_to_user = models.OneToOneField(
        User, null=True, blank=True, on_delete=models.SET_NULL, related_name="User"
    )
    status = models.ForeignKey(Status, null=True, on_delete=models.SET_NULL)
    twitter_id = models.CharField(
        blank=True,
        max_length=32,
        verbose_name="Twitter ID",
        help_text="Enter the Twitter account name of the artist, if known (without the Twitter URL)",
    )
    webpage = models.URLField(
        blank=True,
        verbose_name="Website",
        help_text="Website for this artist. Must exist on the web.",
    )
    wiki_link = models.URLField(
        blank=True, help_text="URL to Wikipedia entry (if available)"
    )
    scene_relevance = models.TextField(
        blank=True,
        help_text="The artist's demoscene relevance. So the mods can approve it faster",
    )

    def __str__(self):
        return f"{self.id} - {self.handle}"

    @property
    def is_deceased(self):
        return self.deceased_date is not None


class Song(models.Model):
    LEGACY_FLAG = (
        (
            " ",
            "N/A",
        ),  # Is not a legacy tune (new upload since Jul. 2018, or replaced streamrip)
        (
            "R",
            "Recovered",
        ),  # is a recovered stream rip (not original, needs replacement)
        ("M", "Missing"),  # existed in Old Necta but is present now
    )

    title = models.CharField(
        verbose_name="* Song Name",
        help_text="The name of this song, as it should appear in the database",
        max_length=80,
        db_index=True,
    )
    bitrate = models.IntegerField(blank=True, null=True)
    explicit = models.BooleanField(
        default=False,
        verbose_name="Explicit Lyrics?",
        help_text="Place a checkmark in the box to flag this song as having explicit lyrics/content",
    )
    file = models.FileField(
        upload_to="media/songs",
        verbose_name="File",
        max_length=200,
        help_text="Select a module (mod, xm, etc...) or audio file (mp3, ogg, etc...) to upload. See FAQ for details.",
    )
    locked_until = models.DateTimeField(blank=True, null=True)
    loopfade_time = models.PositiveIntegerField(
        default=0, verbose_name="Forced play time", help_text="In seconds, 0 = disabled"
    )
    playback_fadeout = models.BooleanField(
        default=True,
        verbose_name="Fadeout at end",
        help_text="Only active if Forced play time is set",
    )
    playback_bass_mode = models.CharField(
        max_length=4,
        choices=(
            ("pt1", "ProTracker 1"),
            ("ft2", "FastTracker2"),
            ("bass", "Bass"),
        ),
        blank=True,
        verbose_name="Playback mode",
    )
    playback_bass_inter = models.CharField(
        max_length=6,
        choices=(("off", "Off"), ("linear", "Linear"), ("sinc", "Sinc")),
        blank=True,
        verbose_name="Playback interpolation",
    )
    playback_bass_mix = models.CharField(
        max_length=4,
        choices=(("Auto", "auto"), ("0.0", "Off"), ("0.3", "Mix"), ("0.5", "Mono")),
        blank=True,
        verbose_name="Playback Mix",
    )

core/views.py
from django.views.generic import ListView

from .models import News


class HomePageView(ListView):
    def get_queryset(self, **kwargs):
        return News.objects.order_by("-created_at")[:10]

core/templates/base/base.html
{% extends "base/base_skeleton.html" %}
{% load dv_extend %}
{% load cache %}

{% block content %}
    <div id="sidebar">
        <h3>Welcome, {% if user.is_authenticated %}{{ user }}{% else %}Visitor{% endif %}!</h3>
        {% block sidebar %}
        <ul class="menulist">
            <li id="home"><a href="{% url 'core:home' %}">Home</a></li>
            <li id="forum"><a href="#">Forum</a></li>
            <li id="songs"><a href="{% url 'radio:songs_list' %}">Songs</a></li>
            <li id="song-source"><a href="#">Sources</a></li>
            <li id="song-platform"><a href="{% url 'radio:platforms_list' %}">Platforms</a></li>
            <li id="artists"><a href="{% url 'radio:artists_list' %}">Artists</a></li>
            <li id="groups"><a href="#">Groups</a></li>
            <li id="labels"><a href="#">Labels</a></li>
            <li id="compilations"><a href="#">Compilations</a></li>
            <li>&nbsp;</li>
            <li id="menuqueue"><a href="#">Queue</a></li>
            <li>&nbsp;</li>
            <li id="search"><a href="#">Search</a></li>
            <li id="recent"><a href="#">New Uploads</a></li>
            <li>&nbsp;</li>
            <li id="faq"><a href="#">FAQ</a></li>
            <li id="links"><a href="#">Links</a></li>
        </ul>
        {% endblock %}
        <br />
        <h3>Infamous OneLiner</h3>
        {% if user.is_authenticated %}
        <form action="#" method="post" enctype="application/x-www-form-urlencoded"  onsubmit="apf('#',this); this.Line.value = ''; return false;" >
            <input id="blah" name="Line" autocomplete="off" maxlength="256" onkeydown="return tc(this,event.keyCode);" onkeypress="return canceltab(event.keyCode);" value="GURU MEDITATION" onfocus="if (this.value == 'GURU MEDITATION') { this.value=''; }" /><input id="makeitso" type="submit" value="" />
            <div class="onelinertools"></div>
        </form>
        {% endif %}
        {# get_oneliner #}
        <a href="#">Oneliner History</a>
    <br /><br />
        <h3>Who's Online?</h3>
    {% cache 60 whosonline %}
        {# get_online_users #}
    {% endcache %}
    </div>

    <div id="rightside">
        <h3>User Menu</h3>
        <div class="message-display-settings">Notification settings</div>
        <ul>
        {% if user.is_authenticated %}
            <li id="profile"><a href="#">Edit My Profile</a></li>
            <li id="favorites"><a href="#">My Favourites</a></li>
            <li id="inbox"><a href="#">My Inbox {# get_inbox user #}</a></li>
            <li id="logout"><a href="#">Log Me Out</a></li>
        {% else %}
            <li id="login"><a href="#">Log In / Register</a></li>
        {% endif %}
        {% if user.is_staff %}
            <li id="admin"><a href="#" target="admin">Admin Area</a></li>
        {% endif %}
        {% if perms.webview.change_song %}
            <li id="menuqueue"><a href="#">Unapproved Uploads</a></li>
        {% endif %}
        {% if perms.webview.add_mute_oneliner %}
                <li id="menumute"><a href="#">Mute account</a></li>
        {% endif %}
        {% if user.is_staff %}
        <li></li>
        {% if perms.webview.change_artist %}
            <li id="unap-artists"><a href="#">Pending Artists</a></li>
        {% endif %}
        {% if perms.webview.change_group %}
            <li id="unap-groups"><a href="#">Pending Groups</a></li>
        {% endif %}
        {% if perms.webview.change_label %}
            <li id="unap-labels"><a href="#">Pending Labels</a></li>
        {% endif %}
        {% if perms.webview.change_link %}
            <li id="unap-links"><a href="#">Pending Links</a></li>
        {% endif %}
        {% endif %}
        </ul>
        <br />
        <h3>Currently Playing</h3>
        <div data-name="nowplaying">
        {#% current_song %#}
        <div>
        {# {% get_rating_stars_song_avg user %} #}
        </div>
        </div>

    <form>
        <hr style="width: 80%; background-color: #000; height: 1px; border: 0px;" />
        <input type="button" style="border: 1px solid; border-color: #333;" value="Listen" onClick="window.open('#','player','width=340,height=25,toolbar=no,scrollbars=no,resizable=no,location=no,directories=no,status=no,menubar=no,copyhistory=no')" /> - <a href="#">Streams</a>
    </form>

    {# get_sidebar_news #}
        {% for sbnews in sidebarnews %}
        {% cache 3600 "sidebarnews" sbnews.id sbnews.last_updated %}
            <br />
            <h3>{{ sbnews.title }}</h3>
            {{ sbnews.text|safe }}
        {% endcache %}
    {% endfor %}

    </div>

    <div id="main">
    {% cache 1 logoblock %}<h1>{% site_name %}</h1>
    <div style="overflow:hidden">{% logo %}</div>{% endcache %}
    <div style="overflow:auto" id="maincontent">
        {% block main %}{% endblock %}
    </div>
    <div id="footer">
        <span id="copyleft">
        Powered by <a href="#">Demovibes</a><br />
        </span>
        <span id="copyright">
        layout: <a href="http://raina.daug.net/">raina</a>,
        icons: <a href="http://www.famfamfam.com/"><span style="color: #f15;">fam</span><span style="color: #1cf;">fam</span><span style="color: #bf3;">fam</span></a>
        </span>
    </div>
    </div>


{% endblock %}

core/templates/base/base_other.html
{% extends "base/base.html" %}
{% block sidebar %}
        <ul>
            <li id="home"><a href="{% url dv-root %}">Home</a></li>
            
            <li id="song-platform"><a href="{% url dv-song-platform %}">Song Platforms</a></li>
        </ul>
{% endblock %}

core/templates/base/base_skeleton.html
{% load dv_extend %}{% load static %}<!DOCTYPE html>
<html lang="en" {% block html %}id="base"{% endblock %}>
  <head>
    {% block earlyheadblock %}{% endblock %}
    <link rel="stylesheet" href="{% static 'themes/base.css' %}" type="text/css" />
    <link rel="stylesheet" href="{% static 'themes/default/style.css' %}" type="text/css" />
    <link rel="icon" type="image/vnd.microsoft.icon" href="{% static 'favicon.ico' %}" />
    <title>{% block title %}Welcome{% endblock %} - {% site_name %}</title>
    <meta name="Description" content="Demovibes Demoscene Radio - your 24/7 source of demoscene music" />
    <meta name="Keywords" content="demoscene, demo scene, scene music, scenemusic, radio, stream, streaming, demovibes, demo vibes, nectarine, necta" />
    <script src="{% static 'js/jquery.min.js' %}" type="text/JavaScript"></script>
    <sscript src="{% static 'js/dutils.js' %}" type="text/JavaScript"></script>
    <sscript src="{% static 'js/dobject.js' %}" type="text/JavaScript"></script>
    <sscript src="{% static 'js/dtabcomplete.js' %}" type="text/JavaScript"></script>
    <script src="{% static 'js/jquery.qtip.min.js' %}" type="text/JavaScript"></script>
    <script src="{% static 'js/sort/tablesort.min.js' %}" type="text/JavaScript"></script>
    <script src="{% static 'js/jquery/popup.js' %}" type="text/JavaScript"></script>
    <script>
    STATIC_URL = "{% static '' %}";
    </script>
    {% block headblock %}{% endblock %}
  </head>
  <body {% block bodyid %}id="site"{% endblock %} onload="nope_ajaxmonitor({# ajaxevent #});" onunload="nope_ajaxmonitorabort();">
    {% block content %}{% endblock %}
  </body>
</html>

core/templates/base/error.html
{% extends "base/base.html" %}

{% block main %}
<h2>Error</h2>
{{ error }}
{% endblock %}